### ISSUE TITLE
DOMNode what for?

### ISSUE THREAD

**Issue by fabriziogiordano** [EvanBacon/Expo-Pillar-Valley#2]
Great Project!

Can you explain the use for https://github.com/EvanBacon/Expo-Pillar-Valley/blob/master/window/domElement.js#L4 and all the JS files in the window folder?

Thanks!

**Comment by EvanBacon** [comment]
Generally I use these files for stubing out features that certain libs call. For instance pixi.js uses all of this. I believe DomNode in particular is used for TweenMax support <3 the touches is what I was using before I added the better TouchableView. Resize is used for things that measure the window or update orientation

**Comment by fabriziogiordano** [comment]
@EvanBacon  I am studying the code and it is so great. I am learning a lot. The THREE part is quite complex. It would be nice if you could write a post or I might write it in a couple of weeks once I am done dissecting all the lines of code you wrote.
